name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: ./gradlew install
      - name: Run tests
        run: ./gradlew test
      - name: Build library
        run: ./gradlew build
      - name: Publish
        run: ./gradlew publish
        env:
          version: 1.0.${{ github.run_number }}
          gh_username: GitHub
          gh_token: ${{ github.token }}
