name: build

on:
  push:
    branches:
      - main
    paths:
      - src/main/**/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: ./gradlew install
      - name: Run tests
        run: ./gradlew test
      - name: Build library
        run: ./gradlew build
      - name: Publish
        run: ./gradlew publish
        env:
          version: 1.0.${{ github.run_number }}
          gh_username: GitHub
          gh_token: ${{ github.token }}
          bintray_user: romanlamsal
          bintray_api_key: ${{ secrets.BINTRAY_API_KEY }}
          bintray_vcs_url: https://github.com/${{ github.repository }}.git
