name: build-service-1

on: push

jobs:
  build-service-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: ./gradlew install
      - name: Run tests
        run: ./gradlew test
      - name: Build library
        run: ./gradlew build
