name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: ./gradlew install
      - name: Run tests
        run: ./gradlew test
      - name: Build library
        run: ./gradlew build
      - name: Publish
        run: ./gradlew publish -Pusername=GitHub -Ptoken=${{ secrets.GITHUB_TOKEN }}
